### ISSUE TITLE
File missing

### ISSUE THREAD

**Issue by rodluger** [mkenworthy/V773TauBdisk#1]
The current build is failing because ``V773_SPHERE_median.fits`` can't be found:

https://github.com/mkenworthy/V773TauBdisk/runs/7248789534?check_suite_focus=true#step:3:205

Where should this file be obtained from? Let me know if I can help debug!

**Comment by mkenworthy** [comment]
My issue is that I’m trying to put the static data in a sandbox Zenodo, and I thought I had activated this correctly, but when I try to push the cache to zenodo it says there are no files to transfer… I’ve added ‘cached:True’ for the dynamically large built emcee chain files, but these do not seem to be transferred up to Zenodo. I’ll have another look and see what’s going on.

I’d like to just add the static files to the repo directly for now, so that I can go ahead and put the paper on arXiv, but I know that’s not an ideal workflow…

Matt

**Comment by rodluger** [comment]
Can you push your latest changes to main? I don't see the `cache` option set in the Snakefile.

**Comment by mkenworthy** [comment]
okay, I've made the Zenodo repo and added it into showyourwork.yml but the build process does not seem to be able to access the publically accessible zenodo repo... any ideas how to resolve this are appreciated!

**Comment by rodluger** [comment]
I think the issue is with your indentations in your YAML file. See #2  -- that should fix it!

**Comment by rodluger** [comment]
The issue now is that `analyze_and_plot_C_orbit_bundle.py` depends on  `v773_tau_C_AB_bary_preselected_orbparams.hdf5`, but you haven't told `showyourwork` about that dependency. So it doesn't download it from the Zenodo deposit, leading to [this error](https://github.com/mkenworthy/V773TauBdisk/runs/7323434986?check_suite_focus=true#step:3:187). You should list all the script dependencies explicitly like you started doing [here](https://github.com/mkenworthy/V773TauBdisk/blob/main/showyourwork.yml#L18). Note that you should also merge the two `dependencies:` entries into a single one.

**Comment by mkenworthy** [comment]
Okay, I've made progress - it's now finding all the files.
The latest problem is that `v773_tau_AB.hdf5` is generated by `make_v773_tau_AB_bundle.py`, which has replaced `make_v773_tau_AB_bundle_notebook.py` and I've adjusted the rule in `Snakemake` accordingly. Why did I originally run a Notebook to generate the bundle? Because there's some bug that causes `orbitize` to choke in a .py but not in .ipynb - but this now seems to have disappeared, so I'm reverting back to `make_v773_tau_AB_bundle.py`.

Here's the problem: github may time out on running `make_v773_tau_AB_bundle.py` to make `v773_tau_AB.hdf5`, BUT I know that the `v773_tau_AB.hdf5` in Zenodo is the correct output file and it doesn't need rerunning of `make_v773_tau_AB_bundle.py` to regenerate it... but this might happen each time someone pulls down this repo, which will take a long time and makes the Zenodo file somewhat redundnant... is there a way of saying to showyourwork 'no, really, the Zenodo file is the correct one and you don't need to rerun?'.

Many thanks for your patience with me on this....

**Comment by rodluger** [comment]
The way caching works is Snakemake computes the checksum/hash of all the files/rules upstream of a given rule. If that hash matches the hash on Zenodo, showyourwork skips the rule and restores the file from cache. So if everything upstream of the rule is unchanged, it should never re-run the rule, whether it's you, the GitHub Actions runner, or a third-party user who cloned your repo. You do have to publish the Zenodo deposit, either by running `showyourwork cache freeze` (publishes it on Sandbox) or `showyourwork cache publish` (publishes it for real, on Zenodo).

**Comment by rodluger** [comment]
That said, it looks like your cache DOI is set to `null` in your `zenodo.yml` file. Did you remove it?

**Comment by mkenworthy** [comment]
Yes, I decided to skip the sandbox and went straight to publishing the Zenodo and linking it in the show your work directly. It seems that this is working, it’s now down to how it handles this file generation. If nothing else, I’ll just comment that workflow out for now. I want to see the paper pdf being generated!

Matthew Kenworthy // Leiden Observatory // https://kenworthy.space/

**Comment by rodluger** [comment]
Hoorah! https://github.com/mkenworthy/V773TauBdisk/runs/7343128880?check_suite_focus=true

**Comment by mkenworthy** [comment]
Wonderful! Many thanks Rod, it’s a relief to finally see it working. Now I have to decode why orbitize! Tables read in successfully for me but not on the GitHub action, and why the star symbols have disappeared in the orbitize! Plots...

Many many thanks!

Matt
